### ISSUE TITLE
minTime/maxTIme  renderHelper Bug

### ISSUE THREAD

**Issue by mlaufer** [fullcalendar/fullcalendar-scheduler#138]
Hello,

I just tried the negative minTime/more than 24h maxTime feature, which you implemented with #112 and there is a bug with `FC.TimeGrid.Grid.renderHelper`, more specifically with `FC.TimeGrid.Grid.computeDateTop`. 

When you drag an event onto the negative minTime section or the "more than 24h" maxTime section, it seems like its not rendered, but its just the `top` and `bottom` values, which are 0.

Fiddle: http://jsbin.com/cixuwosibe/1/edit

Regards

**Comment by arshaw** [comment]
ah. negative minTime has been made to work with *timeline* view, but not yet with agenda view like you desire. This is more of a "core" issue since it deals with agenda view. Can you please follow this issue? i've moved your issue over to core:
https://github.com/fullcalendar/fullcalendar/issues/3055
