### ISSUE TITLE
nowIndicator nothing update with render!

### ISSUE THREAD

**Issue by emalherbi** [fullcalendar/fullcalendar-scheduler#182]
Hi.

Why does this happen? 

![captura de tela 2016-06-01 as 11 11 31 pm](https://cloud.githubusercontent.com/assets/599674/15731814/3baced12-284e-11e6-8d77-61d91062e115.png)

I tried it:

```js
$('#calendar').fullCalendar('getView').calendar.options.nowIndicator = true;
$('#calendar').fullCalendar('render');
```

**Comment by emalherbi** [comment]
![captura de tela 2016-06-01 as 11 21 34 pm](https://cloud.githubusercontent.com/assets/599674/15731988/a2c985e0-284f-11e6-828b-fa90196830c8.png)

work if I do:

```js
$('#calendar').fullCalendar( 'changeView', 'month' );
$('#calendar').fullCalendar( 'changeView', 'agendaDay' );
```

**Comment by arshaw** [comment]
Thanks for your submission. A bug can be fixed much more effectively when recreated in a minimal test environment. Could you please create a runnable [Reduced Test Case](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? This will save a great deal of time, and is very appreciated.

**Comment by arshaw** [comment]
Looking further at your technique, i'm realizing the problem is occurring because setting the `.calendar.options.` properties and then rerendering is an unsupported way to change options, and will be error prone.

This issue addresses the ability to set ANY option dynamically after initialization:
https://github.com/fullcalendar/fullcalendar/issues/564 (in the core project)
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.
