### ISSUE TITLE
Issue with scrollTime and call $('#calendar').fullCalendar('prev'); from script

### ISSUE THREAD

**Issue by Tikia** [fullcalendar/fullcalendar-scheduler#201]
How to reproduce the issue : 
- go here : http://sd-67171.tikia.net/dev/fullcalendar-scheduler-reduced-test-case/
- put mouse over the calendar
- do an horizontal scroll with mouse (easy with a Mac, shift + scroll on Windows, i think) : scroll to the left (it look lik you can also directly move the scrollbar)
- when you reach the begining (there is a scrollTime so you can scroll left) you will jump do previous day

If you look the disply after jumping to previous day, you can see the issue :
- the scrolltime apply correctly but you can't scroll left (between 9:30 and 9:00)
- the background event is 9:30 to 10:30 but he end at 10:30
- when you scroll right, and go back left, display is ok

I hope my description is understandable... And sorry for my bad english.

**Comment by arshaw** [comment]
I see you are doing some tricky custom code to get this pseudo-endless-scroll to work. The problem might be with how your code interacts with the API, not with the API itself. To determine if that is/isn't the case, I would really appreciate if you could put your source code in a runnable demo so that someone can begin debugging: [Reduced Test Case](http://fullcalendar.io/wiki/Reduced-Test-Cases/)
