### ISSUE TITLE
updateEvent is updating all events that share the same ID

### ISSUE THREAD

**Issue by alannaidon** [fullcalendar/fullcalendar-scheduler#209]
### JsBin Example
https://output.jsbin.com/suyako

### Description:  
The `updateEvent` documentation says:  

>Reports changes to an event and renders them on the calendar.
>.fullCalendar( 'updateEvent', event )
>event must be the original Event Object for an event, not merely a reconstructed object. The original >Event Object can obtained by callbacks such as eventClick, or by the clientEvents method.  

This method updates `All the events that share the same ID`. I don't know if it's supposed to happen, the documentation does not say anything about this.  

I know that `IDs` should be uniques and I if more than one event has the same information, then I should use `Class` instead. But in my case, I'm using both already.  Is it an expected behavior ?  

Also, if you look the `eventTitle` is also changing.  
I'd like to change the color only, and only that specific event.

**Comment by arshaw** [comment]
Hi @alannaidon, that is by design, all events with the same ID are pretty tightly linked. I'll make a note to document this better. You can workaround this by making their ID's different, and defining the relationship between them by some other means, a custom property maybe. That will unfortunately cause them to stop dragging to together, but not sure if you're relying on that behavior.
