### ISSUE TITLE
Date range wrong in custom timeline view

### ISSUE THREAD

**Issue by BsSithu** [fullcalendar/fullcalendar-scheduler#239]
When set custom timeline view as following.
```
views: {
  timelineCustomMonth: {
    type: 'timeline',
    duration: { days: day_range, },
    slotDuration: {days: 1},
  }
},
```
And, set `defaultDate` to **12/01/2016** and set `day_range` to **7** so end date is **12/07/2016**. But, day range render is totally wrong on **7, 14, 21, 28** days. Above the code result day range render should be **Dec 1 - Dec 7 2016** but the actual result is **Nov 27 - Dec 3 2016**. Additionally, if `defaultDate` is set to **11/29/2016**, the result worng at **5, 12, 19, 26**. I make highlight at the following pics. You can see my test code is [here](https://jsbin.com/linikixehe/edit?html,js,output).

![calendar](https://cloud.githubusercontent.com/assets/23631873/20786739/2930be44-b7d6-11e6-83f4-d9827f229925.jpg) ![calendar2](https://cloud.githubusercontent.com/assets/23631873/20787193/f9ab3d72-b7d8-11e6-9e7c-bd58bf085971.jpg)

**Comment by arshaw** [comment]
That's because 7 days, or a multiple of 7, is inferred as a week and aligns to the beginning of the week. As-designed behavior but undesired in your case. Ticket that describes a solution:
https://github.com/fullcalendar/fullcalendar/issues/2847
&uarr;
Could you please visit the link, **give a** 👍  **to vote to the top description** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

the comment that contains my proposed solution:
https://github.com/fullcalendar/fullcalendar/issues/2847#issuecomment-225390620
