### ISSUE TITLE
module import without side effects

### ISSUE THREAD

**Issue by hsreina** [fullcalendar/fullcalendar-scheduler#249]
It would be great to be able to use fullcalendar-scheduler using 
`import FullCalendarScheduler from 'fullcalendar-scheduler'`

Now, if we import 'fullcalendar-scheduler' using import functions, the code give us an unusable empty object.
Is it possible for you to return FC in outro.coffee to let us use it? Just like you did in fullcalendar outro.js
[https://github.com/fullcalendar/fullcalendar/blob/master/src/outro.js#L2](https://github.com/fullcalendar/fullcalendar/blob/master/src/outro.js#L2)

If you do that, the full caendar lib return should include the scheduler.

Thank you

**Comment by arshaw** [comment]
Both the core initialization, and the scheduler initialization, are written as jQuery plugins, so I'm not sure what good an object would be unless the way a Calendar/Scheduler is initialized is also changes.

I'll leave this open for discussion. `new Calendar(options)` ? Since "Scheduler" is essentially just new additional views, how would that work. There'd need to be more thought into API design on this one.

**Comment by roninee** [comment]
how could I import the fullcalendar-scheduler in scheduler alpha2?
At the past I user scheduler in scripts, it's like
`
<script src="/js/scheduler/fullcalendar.min.js"></script>
<script src="/js/scheduler/scheduler.js"></script>
`
it can be worked,  these events has many diffrent colors。
but now I am studying nodejs, i check the example :

**Comment by roninee** [comment]
hi, arshaw.
I want to how import the fullcalendar-**scheduler alpha.2 in parcel**?
At the past I user scheduler in scripts, it's like
```
<script src="/js/scheduler/fullcalendar.min.js"></script>
<script src="/js/scheduler/scheduler.js"></script>
```
it can be worked, these events has many diffrent colors。
but now I am studying nodejs, i do it like the example :
```
import $ from 'jquery';
import 'fullcalendar';
import 'fullcalendar-scheduler';
```
it didn't work,i change it to :
```
import $ from 'jquery'
import { Calendar } from 'fullcalendar';
import 'fullcalendar-scheduler'
var calendarEl = document.getElementById('calendar');
new Calendar(calendarEl, ....
```
then it did work,but the **scheduler** did not work, because i see the default color on every events, 
So, how could import the scheduler correctly?
I am running on the :
NodeJS 10.13 on windows 10；
parcel(not webpack) ；1.10.3
fullcalendar &scheduler alpha.2。

**Comment by roninee** [comment]
> Both the core initialization, and the scheduler initialization, are written as jQuery plugins, so I'm not sure what good an object would be unless the way a Calendar/Scheduler is initialized is also changes.
> 
> I'll leave this open for discussion. `new Calendar(options)` ? Since "Scheduler" is essentially just new additional views, how would that work. There'd need to be more thought into API design on this one.

hi, arshaw.
I want to how import the fullcalendar-**scheduler alpha.2 in parcel**?
At the past I user scheduler in scripts, it's like
```
<script src="/js/scheduler/fullcalendar.min.js"></script>
<script src="/js/scheduler/scheduler.js"></script>
```
it can be worked, these events has many diffrent colors。
but now I am studying nodejs, i do it like the example :
```
import $ from 'jquery';
import 'fullcalendar';
import 'fullcalendar-scheduler';
```
it didn't work,i change it to :
```
import $ from 'jquery'
import { Calendar } from 'fullcalendar';
import 'fullcalendar-scheduler'
var calendarEl = document.getElementById('calendar');
new Calendar(calendarEl, ....
```
then it did work,but the **scheduler** did not work, because i see the default color on every events, 
So, how could import the scheduler correctly?
I am running on the :
NodeJS 10.13 on windows 10；
parcel(not webpack) ；1.10.3
fullcalendar &scheduler alpha.2。

**Comment by roninee** [comment]
hi, arshaw.
I want to how import the fullcalendar-**scheduler alpha.2 in parcel**?
At the past I user scheduler in scripts, it's like
```
<script src="/js/scheduler/fullcalendar.min.js"></script>
<script src="/js/scheduler/scheduler.js"></script>
```
it can be worked, these events has many diffrent colors。
but now I am studying nodejs, i do it like the example :
```
import $ from 'jquery';
import 'fullcalendar';
import 'fullcalendar-scheduler';
```
it didn't work,i change it to :
```
import $ from 'jquery'
import { Calendar } from 'fullcalendar';
import 'fullcalendar-scheduler'
var calendarEl = document.getElementById('calendar');
new Calendar(calendarEl, ....
```
then it did work,but the **scheduler** did not work, because i see the default color on every events, 
So, how could import the scheduler correctly?
I am running on the :
NodeJS 10.13 on windows 10；
parcel(not webpack) ；1.10.3
fullcalendar &scheduler alpha.2。

**Comment by arshaw** [comment]
v4 achieves this. i'll comment again on this issue when v4 is officially released

**Comment by arshaw** [comment]
[V4 was officially released a few days ago!](https://fullcalendar.io/blog/2019/03/v4-officially-released)
