### ISSUE TITLE
In agendaWeek View if i add an event in with allDay:true then the whole day should be unselected

### ISSUE THREAD

**Issue by dbaprateekagrawal** [fullcalendar/fullcalendar-scheduler#260]
I have a question : In agendaWeek View if i am adding an event in with allDay:true then the whole day should be unselected . dayclick will not work on rest of time slot

is this possible ...please help

**Comment by arshaw** [comment]
Is this a bug report or a feature request? If a bug, report, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

If it's simply a question about what's possible, see Getting Help:
https://fullcalendar.io/support/
