### ISSUE TITLE
Set businessHours for Resource on selfmade schedule

### ISSUE THREAD

**Issue by NoNameWhatever** [fullcalendar/fullcalendar-scheduler#304]
I came across a limitation that I can't find any function for, nor a request of.

If you are using the Resource as technicians. And these technicians are working on a shift schedule.

You then want to have individual business hours for each resource. This you can do. As long as it's based on 7 day week.

If you have resources working on shift, with repeating schedule on a 8 day basis, or 17 day basis. You would want to be able to set business hours on that basis.

So I been thinking about some code how to do that. Just to be able to explain better.

```
$('#calendar').fullCalendar({
    defaultView: 'timelineWeek',
    resources: [
        {
            id: 'a',
            title: 'Resource A',
	    businessBasis: { days: 17 },	//Which basis the schedule is based on. Could have days, weeks
	    businessStart: '2017-04-27',	//Which day the repeated schedule begins.
            businessHours: [
		{
			dib: [ 1, 2, 3 ], // Day-In-Basis. Number of day in the basis. 1 would be = businessStart
			start: '08:00', // As usual start os business
			end: '18:00' // And end of business
		},
		{
			dib: [ 4, 5 ], // 
			start: '08:00', // 
			end: '20:00' // 
		},
		{
			dib: [ 12, 13, 14 ], // 
			start: '08:00', // 
			end: '17:30' // 
		}
            ]
        },
        {
            id: 'b',
            title: 'Resource B',
	    businessBasis: { days: 9 },	//Which basis the schedule is based on. Could have days, weeks
	    businessStart: '2017-04-26',	//Which day the repeated schedule begins.
            businessHours: [
		{
			dib: [ 1, 2, 3, 4 ], // Day-In-Basis. Number of day in the basis. 1 would be = businessStart
			start: '08:00', // As usual start os business
			end: '18:00' // And end of business
		}				
            ]
        }
    ]
});
```

**Comment by arshaw** [comment]
hi @NoNameWhatever thanks for the thought you put into this, but when **recurring events** is implemented, which is a highly-demanded feature in the core project ([see ticket](https://github.com/fullcalendar/fullcalendar/issues/387)), I will make it so that business hours can be defined in the same way. It will likely resemble an iCal style rrule scheme ([link](https://github.com/jakubroztocil/rrule))

again, the recurring events ticket:
https://github.com/fullcalendar/fullcalendar/issues/387
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Comment by NoNameWhatever** [comment]
Hi arshaw. Thank you for taking time to answer. I think I didn't explain enough. I'm not talking about events.

It's the business hours.

I believe the business hours are meant to represent which time the resource is available for events.

If a resource have a irregualar schedule, not based on week, month or so. But on a user defined regularity.

Like.
Work 4 days. Off 4 days. Work 7 days. Off 7 days -> repeat

Then it would be nice to set business hours for that schedule. Not only a schedule based on a week regularity.

So, not reccuring events. But business hours for resources.
