### ISSUE TITLE
selectOverlap missing current selected period

### ISSUE THREAD

**Issue by GidanMX2** [fullcalendar/fullcalendar-scheduler#312]
Hi,
I think that when selectOverlap parameter is defined as a function, It would have an extra argument contain the current selected period, otherwise is not possible to have a full control over the overlap.

Es. 
I have a event in a timeline view that ends on 19/05/2017 at 10:00 and I need to create the second who start on 19/05/2017 at 10:20, then I need to start selection from the last day of the first event. In this case, the selection overlaps with an event but I need to allow this, while I need to overlap for previous days.

If selectOverlap did have the `currentSelection` argument I could write this check:

```
selectOverlap: function(stillEvent,currentSelection){
                if(currentSelection.start>=stillevent.end){
                    return true;
                } else {
                    return false;
                }
            }
```
What do you think?

**Comment by arshaw** [comment]
The `selectOverlap` callback is meant to be called for every time a user's selection overlaps with an event. It will then ask the callback "is it okay of the selection overlaps this event?". If the user makes a selection that does not overlap with any events, `selectOverlap` will not be called.

In your hypothetical example, the selection period happens completely after the `stillEvent`, so in this case selectOverlap would not be called at all.

The [selectAllow](https://fullcalendar.io/docs/selection/selectAllow/) callback operates more closely to what you request because it is executed *any* time the user makes a selection. However, that callback does not receive any information about events.

I would suggest writing logic in a `selectAllow` callback that queries for events (via [clientEvents](https://fullcalendar.io/docs/event_data/clientEvents/)). Does that make sense?

**Comment by ph-kaelin** [comment]
as written by GidanMX2 it would be helpful to have both events.
Like in eventOverlap.
eventOverlap: function(stillEvent, movingEvent)

I can't implement my check and to do it with selectAllow is much more work.

But thank anyway to provide such a great calender control !!!
