### ISSUE TITLE
Circular Structure when using clientEvents

### ISSUE THREAD

**Issue by bgsnyder** [fullcalendar/fullcalendar-scheduler#316]
When using **clientEvents** I get an error :    **circular structure to JSON...**

Example: alert(JSON.stringify($('#calendar').fullCalendar('clientEvents'));

Use the code pen link and click the Run button at the bottom.
Notice the error in the console.

https://codepen.io/anon/pen/QgjGdG

**Comment by arshaw** [comment]
the objects returned from `clientEvents` have references to other complex objects and are not meant to be serialized directly.

The solution is for you to loop through these objects and make an array of your own objects, objects that are simpler and that can be serialized. This is a good technique because it also allows you to include additional properties and exclude ones you don't care about.
