### ISSUE TITLE
Timeline multiple day view

### ISSUE THREAD

**Issue by Patatou** [fullcalendar/fullcalendar-scheduler#34]
Hi,

When you're in timeline with multiple day view, if slotDuration < 00:10:00 scroll with day name disapear.

Strange...

**Comment by Patatou** [comment]
Ok, problem appear only when slotDuration < 00:10:00 and you not specify slotLabelFormat

**Comment by arshaw** [comment]
would you mind posting a  JSBin recreation?
http://fullcalendar.io/wiki/Reporting-Bugs/

see "Scheduler Add-on > simple template"

**Comment by arshaw** [comment]
demo of things "working":
http://jsbin.com/ciluso/1/edit?js,output

what you are experiencing is desired behavior because you probably only are showing a single day. if you show multiple days, the day header will appear

or you can customize it with slotLabelFormat
http://fullcalendar.io/docs/timeline/slotLabelFormat/
