### ISSUE TITLE
Should "selectOverlap:false" be connected to "renderEvents" ?

### ISSUE THREAD

**Issue by LeoFlandin** [fullcalendar/fullcalendar-scheduler#345]
### If a event is disabled using a custom business logic in renderEvents, selectOverlap: false should not prevent to create a event on this time slot

[JSBIN selectOverlap:false and renderEvents](https://jsbin.com/tanuvefoga)

In this jsbin, there is a recurring event happening between 8 and 10 on every **even** day of mouth (it's a example, the business logic is more meaningful).

## Expected behavior
It should be **impossible**, due to selectOverlap:false, to create a event that intersects with the 8-10 time slot on **even** day.
It should be **possible** to create a event whenever we want on a **odd** day.

## Occurring behavior
It is **impossible**, to create a event that intersects with the 8-10 time slot on **all** days.

## Questions 

1. Shouldn't selectOverlap logic be based on renderEvents logic to check if the time slot if effectively used ?

2. If not, can we have a better callback on selectOverlap, with `start `and `end ` of current selection si that we can inject some logic to allowed or disallow overlap based on current selection and overlapping event ?

**Comment by arshaw** [comment]
Hi @LeoFlandin, I see you are using the secret "dow" to make repeating events, which is not fully supported or documented yet. When it is officially implemented, there will be a notion of an instance "exception" where one of the repeating instances can be omitted or put at a different time. But until more [robust repeat-event features are implemented](https://github.com/fullcalendar/fullcalendar/issues/387), there won't be an elegant solution.

You might want to expand the repeating events on the server-side and send them down as individual events. Your server-side script would be responsible for omitting the ones on the even days.

The easiest workaround is probably this: instead of [selectOverlap](https://fullcalendar.io/docs/selection/selectOverlap/) set to `false`, specify a function that returns `true` when the overlap is on the acceptable event dates. Does that make sense?

**Comment by LeoFlandin** [comment]
Hi Adam, yes I understand. 
For the sake of completeness, there is how I did it : https://jsbin.com/jibejem.
