### ISSUE TITLE
The event does not follow the mouse when dragging and scrolling

### ISSUE THREAD

**Issue by sboele** [fullcalendar/fullcalendar-scheduler#361]
After updating from fullcalendar scheduler 1.5.1 to 1.8.0 we have an issue when dragging events and scrolling down/up to drop it. I was able to reproduce this in a codepen.

Issue in 1.8.0: https://codepen.io/anon/pen/veaXzW
Working in 1.5.1: https://codepen.io/anon/pen/oGMYxp

Check this attached gif for the behaviour in 1.8.0

![0a78075332333237bf932fde799bb97b](https://user-images.githubusercontent.com/1193437/31486849-0d71b748-af39-11e7-8d7f-8bc2e7a6b73c.gif)

And the working version in 1.5.1

![9dc90a4d8c171ec05a817742f8f52a21](https://user-images.githubusercontent.com/1193437/31487024-a295cc9c-af39-11e7-8deb-38dbba051be1.gif)

**Comment by arshaw** [comment]
confirmed. thanks.

**Comment by terrywhiterock** [comment]
Hi arshaw!  Is there an update on this issue?

**Comment by DangerD256** [comment]
Also any way to add automatically scrolling on moving event to the bottom of page?

**Comment by jimmylogic** [comment]
Having same problem

**Comment by jimmylogic** [comment]
+1

**Comment by anatel** [comment]
+1

**Comment by EinarsBistrovs** [comment]
I have the same issue. Are there any news on when this is going to be fixed?

**Comment by arshaw** [comment]
I don't have the bandwidth to fix this in v3, but in v4 this is fixed. proof: https://codepen.io/arshaw/pen/jXeyxB?editors=0010

v4 is in alpha, but the API is stable enough to start using in your projects IMO.

I'll keep this issue upon and circle back when v4 is released

**Comment by dogaoz** [comment]
They changed way too many things in v4... I cannot use my custom fields like job_id in provided events list.... Can't access to those fields inside of eventClick function anymore....

**Comment by dfa1234** [comment]
I'm using 4.0.0.alpha and I have a bug very similar:

![Untitled](https://user-images.githubusercontent.com/8502517/56210080-b536c000-605d-11e9-8460-148797038d21.gif)

**Comment by arshaw** [comment]
@dfa1234 that has been fixed in the official release

the original reported issue has also been fixed in 4.x

**Comment by guillaumeko** [comment]
Hello, are you sure it's been fixed in 4.1 ? I'm using the timeline mode, and get the error (only on Chrome and Firefox), on Safari and Internet Explorer, it's working properly ... As you can see in my gifs, the mouse is not on the event.

Chrome (bug)

![chrome](https://user-images.githubusercontent.com/1857479/62640100-1d791c80-b941-11e9-822c-6299c9a52655.gif)

Firefox (bug)

![Firefox](https://user-images.githubusercontent.com/1857479/62640106-1f42e000-b941-11e9-91ed-14fdc77a5597.gif)

Safari (work)

![Safari](https://user-images.githubusercontent.com/1857479/62640557-1bfc2400-b942-11e9-911e-74ddf68d8629.gif)

Maybe you have same issues ? 

Thanks :)

**Comment by simran-logiciel** [comment]
> I'm using 4.0.0.alpha and I have a bug very similar:
> 
> ![Untitled](https://user-images.githubusercontent.com/8502517/56210080-b536c000-605d-11e9-8460-148797038d21.gif)

I am also having the same bug and does not seems any way how can its be correct
