### ISSUE TITLE
submission to CDNJS

### ISSUE THREAD

**Issue by sashberd** [fullcalendar/fullcalendar-scheduler#384]
Hi guys
We would like to [add ](https://github.com/cdnjs/cdnjs/issues/10156) your library to cdnsj hosting.
I found that you mentioned 3 types of licenses in your README one of them is GPLv3, but how can call for the next 2 (Commercial License and Non-Commercial Creative Commons)?
Thanks for your cooperation

**Comment by acerix** [comment]
I'm not sure what you mean, are you asking what to put next to License(s)?  The full info on licenses is abailable here:

**Comment by arshaw** [comment]
related to this?
https://github.com/fullcalendar/fullcalendar-scheduler/issues/29

**Comment by sashberd** [comment]
@acerix @arshaw 
I mean that we have strict list of licenses (see [here](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json). I can not realize what type/name I should use with your library. (Only GPLv3 is known license name)
If the license is not inside this list,just tell me and we will add it to it in order to support hosting of your lib.
 If you can provide me names of less 2 licenses will glad to use them.
Thanks for cooperation

**Comment by arshaw** [comment]
hi @sashberd , thanks for the work here. Things are a bit complicated because fullcalendar-scheduler is not unconditionally free like most open source libs. It is open source, but released under GPL, under Creative Commons non-CC non-Deriv, and if you want to use it in a commercial project, under a custom-made commercial license.

As such, I don't think it's a good idea to classify it under any of the existing licenses you have. We *could* classify it as GPL, but that'd be missing the commercial license aspect of it.

Is it possible to classify it under a new license, "fullcalendar-scheduler", and somehow link to this page?: https://fullcalendar.io/scheduler/license/

**Comment by sashberd** [comment]
@PeterDaveHello I need you suggestion for this issue. Thanks

**Comment by sashberd** [comment]
@PeterDaveHello ping

**Comment by PeterDaveHello** [comment]
Yes, of course we can do it, we have some libraries using custom licenses.

**Comment by sashberd** [comment]
@PeterDaveHello I will create separate commit with new licence name - "fullcalendar-scheduler" and then I will commit library  itself.
@arshaw Thanks for cooperation
