### ISSUE TITLE
Scheduler is not working in beta environment

### ISSUE THREAD

**Issue by dinhthibc** [fullcalendar/fullcalendar-scheduler#400]
Hi there,
I'm working with scheduler and it works fine in my localhost
However, It doesn't work when I deploy to beta environment
I got the error message in console
```
Uncaught TypeError: Cannot read property 'Mixin' of undefined
```
I'm using `schedulerLicenseKey: 'CC-Attribution-NonCommercial-NoDerivatives'`
I'm not sure it's not working because of free license key

Thanks for your help

**Comment by acerix** [comment]
It sounds like an issue with your webserver, check the server responses in Chrome Devtools, or similar:

https://developers.google.com/web/tools/chrome-devtools/network-performance/reference

It wouldn't be an issue with the license key, the non-commercial key works the same as the commercial one.

If there is an issue with the scheduler, would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

**Comment by FilipLukac** [comment]
same here I've just included fullcalendar-scheduler and this error apears

**Comment by Astriel** [comment]
I've got exactly the same issue by just including fullcalendar-scheduler.

**Comment by acerix** [comment]
Could you post of an example of how you are including the scheduler that causes the error? It should be included like in this example: 

https://fullcalendar.io/releases/fullcalendar-scheduler/1.9.4/demos/simple.html

**Comment by acerix** [comment]
Can you try putting your code in the debug template to reproduce the issue?

I tried included those and didn't get any error:

https://codepen.io/acerix/pen/KRVrYN?&editors=001

Looks like you are including moment locales twice which might be an issue, and also en.js might not exist.

**Comment by McQuinTrix** [comment]
Facing same issue with Fullcalendar 3.9.0 and Schedular @ 1.9.4
