### ISSUE TITLE
event does'nt render properly if dragged/resized over 24h (next day) 

### ISSUE THREAD

**Issue by rayden84** [fullcalendar/fullcalendar-scheduler#420]
If an event in timeline view is dragged or its end is resized over the 24h mark, i . e. into the new day, the event seems to be hidden from the 24h threshold onwards. Once released/resizing done the event is visualized correctly again. 

See: https://codepen.io/anon/pen/rJMpjd

and try to put the event over the 24h mark, i .e. make it later...

P.S.: It seems to behave correctly in timeline views with 3 days

**Comment by acerix** [comment]
Thanks for the detailed report.

I'm not sure `maxTime` later than 24:00 would be supported but there's no documented limit.  

Same issue in Agenda view, so it's not specific to the Scheduler:

https://codepen.io/acerix/pen/yvaKOy?editors=0010

**Comment by rayden84** [comment]
I seem to remember that one of the earlier versions of fullcalendar/scheduler handled this correctly (at least in timeline view). It could be the case that 24h+ was never supported but still correctly handled. Anyway it would be great to have that behavior again (as said, can't remember for sure if it was ever handled correctly).

**Comment by acerix** [comment]
Here is another test case from https://fullcalendar.freshdesk.com/a/tickets/382

https://codepen.io/anon/pen/PBGbxq?&editors=001

Shows that dragging past midnight doesn't work in timeline view in latest version.

**Comment by zbrukas** [comment]
+1

**Comment by zbrukas** [comment]
@acerix is there a way I could help with solving this issue? This repo contains the full source code for the scheduler plugin? Or is this more likely a fullcalender issue? If you can point me to the right direction, I may be more helpful.

**Comment by acerix** [comment]
@zbrukas Yes, all the source code is available on github, so you can take a look at solving this and submit a solution if you find one.  It seems to also be an issue in Agenda view but I'm guessing it's related to how the views are defined, so likely both Agenda (fullcalendar) and Timeline (scheduler) views need to be adjusted.

**Comment by zbrukas** [comment]
@acerix I'm having a hard time trying to find a fix for this. For some reason, the segs are rendered with the `end` property as 12am, although the sourceSeg has it correct, and that is why when the seg is rendered, the `right` css property is wrong, because it'll fetch it from the incorrect time slot.

```
dateToCoord(date) {
    const snapCoverage = this.computeDateSnapCoverage(date)
    const slotCoverage = snapCoverage / this.snapsPerSlot
    let slotIndex = Math.floor(slotCoverage)
    slotIndex = Math.min(slotIndex, this.slotCnt - 1)
    const partial = slotCoverage - slotIndex
    const coordCache = this.slatInnerCoordCache

    if (this.isRTL) {
      return (
        coordCache.getRightPosition(slotIndex) -
        (coordCache.getWidth(slotIndex) * partial)
      ) - this.timeBodyBoundCache.getWidth(0)
    } else {
      return (
        coordCache.getLeftPosition(slotIndex) +
        (coordCache.getWidth(slotIndex) * partial)
      )
    }
  }
```
Slot index should be 51 and it's 43 because the date is somehow wrong. Can you give me a little more guidance? UnzonedRange seems correct, it's on `HelperRenderer::renderEventFootprints` that things go wrong.

**Comment by acerix** [comment]
I just noticed this issue was previously reported:

https://github.com/fullcalendar/fullcalendar/issues/3900
↑
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
