### ISSUE TITLE
time slot % of ocupation across multiple resources.

### ISSUE THREAD

**Issue by devMls** [fullcalendar/fullcalendar-scheduler#431]
Hi.

I am trying to use schecudle, but I need to expose in the week view  a % of ocupation by time slot (no resource dis-agregation in week view).

In a day I see the diferent resources and what is their ocupation (I allow multiple events in the same resource and time), but in the week view I want to show real %:

if i have 3 resources and in a slot time I have 2 resources with 1 event each i want to see 2/3.
if i have 3 resources and in a slot time I have 1 resource with 2 events each i want to see 2/3.
if i have 3 resources and in a slot time I have 0 resource with  events each i want to see 0/3.
if i have 3 resources and in a slot time I have 2 resource with 2 events each i want to see 4/3.
....

the problem is that the events can start and finish in any minute and the slots are of 30 minutes, then:

if i have 3 resources and in a slot time I have 2 resources with 1 event each but the first event is in the 0-14 part of the slot and the second event is in the 15-30 part of the slot i want to see 1/3

schecudler provide any help to implement this value?

thanks

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the issue](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I'm not sure what you are looking for, for example does 2/3 mean 2 resources with at least one event out of 3 resources total?
