### ISSUE TITLE
[bug] Timeline View can not pick time

### ISSUE THREAD

**Issue by sam80719** [fullcalendar/fullcalendar-scheduler#436]
Hi Dear:

I found timelineDay or timelineWeek can not pick the time, it can not pick time such as agendaDay or  agendaWeek even i set the " selectable" to true.....

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

I don't have an issue selecting time slots in timeline views, eg:

https://codepen.io/anon/pen/LmzyBR?&editors=001
