### ISSUE TITLE
drop external events to LIST view

### ISSUE THREAD

**Issue by pizzadev** [fullcalendar/fullcalendar-scheduler#457]
Hi,
Thank you for the awesome library.

I think it would be useful for everyone to have possibility to drop events to "list" view

**Comment by acerix** [comment]
Thanks for the suggestion.  I'm not sure how it the start time of the events would be determined since there are no time slots, are you looking to always have them created at the beginning of the period that is being displayed?

**Comment by acerix** [comment]
Related to https://github.com/fullcalendar/fullcalendar/issues/3529

**Comment by pizzadev** [comment]
For example, last event in list view ends at 13:30.  Then added event should be started at 13:30 by default. Also I would like to have some method (eventDrop is also good for that), where I can customise time and other properties.

**Comment by robertCousineau** [comment]
Hey, did you ever find a workaround for this?

**Comment by arshaw** [comment]
I'm closing this issue because it belongs on the main issue tracker. @robertCousineau  and @pizzadev , could you go to the new issue:
https://github.com/fullcalendar/fullcalendar/issues/3529
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?
