### ISSUE TITLE
Next / Previous button only shows 3 days not five

### ISSUE THREAD

**Issue by ZackTech** [fullcalendar/fullcalendar-scheduler#561]
Next / Previous button only shows 3 days not five, I presume this is a bug unless I am going something wrong?

Don't know how to get this working in JSFiddle but here is the test code:

[Test.txt](https://github.com/fullcalendar/fullcalendar-scheduler/files/3565318/Test.txt)

**Comment by acerix** [comment]
Would you be able to post a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/)? Would really appreciate it because the time saved reproducing will be time spent fixing.

And please use the main issue tracker, this one is no longer in use:

https://github.com/fullcalendar/fullcalendar/issues
