### ISSUE TITLE
Month Timeline view

### ISSUE THREAD

**Issue by MacTwister** [fullcalendar/fullcalendar-scheduler#73]
Hi,

I have a project where I need the kind of view that the schedular provides but instead of a day I would like to see a whole year in my window (no vertical scrolling). So before going ahead with using this plugin, I wanted to do some tests. I can get the veiw if I configure using the slotDuration (months = 1), however the events fill a whole month block instead of starting from a position relating to the date (ie 24th, I would like a rough offset to the right within month and just have the event overlap to the next month, or with a min-width). Summarised, I would like the solt duration to be like a day or week but the view show a month grid.

![calendar-mockup](https://cloud.githubusercontent.com/assets/1853847/11364313/ede708ea-929f-11e5-940f-10b72decd1e9.png)

Any advice or direction to how I could implement this view with your plugin or maybe another way?

Other issues include that I have 800 resources, scrolling is sluggish, but making calendar container have no height, helps with scrolling performance (nice to have as option to configure).

**Comment by arshaw** [comment]
got it. question: once the event starts dragging, how would you proposed it moves across the months/days? a day at a time? snapping to months? in either case, I would imagine some other indicator of the date would be useful. it is hard to tell what date an event is on if it is this granular.

**Comment by jasonEXA** [comment]
Hi @arshaw ,

I have a similar requirement.  Currently working on determining if I can use the scheduler plugin.
![image](https://cloud.githubusercontent.com/assets/9958408/12392393/d1263f1e-be14-11e5-97ef-3ee295a5f2d3.png)

What I am trying to do is to see if I can use the scheduler plugin, in what looks like an agendaWeek view.  Currently, if i use type: agenda instead of type: timeline, the resources just disappear.  Is it possible to use the scheduler to do something like this?

This is for the week/month view.  The event would snap to a day at a time just like how it does in agendaMonth view.  If more granular control is required, the user can simply change to the day view and drag the end of the event to have more control over the end time as opposed to just the end of the day.

**Comment by jasonEXA** [comment]
@arshaw Figured it out, if I use slotDuration: '24:00:00' the timeline gets removed leaving only days.  @MacTwister Shouldn't the slotDuration attribute suit your requirement too?

**Comment by arshaw** [comment]
might be more proper to write `{days: 1}` for slotDuration, but glad you figured it out

**Comment by arshaw** [comment]
i guess, the original issue is still outstanding

**Comment by MacTwister** [comment]
Hi sorry late reply. Erm, So my defaultTimeline view is timelineYear and and slotDuration of 1 month to get the view I want, but then the events are filling a whole month just like they do in the normal full calendar views. But I still would like each vertical column grouped by month so I can fit a whole year on my screen with our having to scroll horizontally with my mouse. 

If I put the slotDuration to 1 day (or 24hrs) then my view is January,January,January,JanuaryJanuary,...., February,February,February,February, ....etc. 

About dragging, yes is a tricky one, as it could be application specific, but I imaging a snipTo property for day, week, month like.

**Comment by jasonEXA** [comment]
@MacTwister  I think this feature is already present.  You would have to use it in combination with slotDuration.
I was able to have a month view and have the event last for 24 hrs with the following configuration,
```
slotDuration : { days: 31 },
snapDuration : '24:00:00'
```

**Comment by arshaw** [comment]
Seems like you guys figured this out using `slotDuration` and `snapDuration`. @jasonEXA i would do `slotDuration: { months: 1 }` because not all months are 31 days long.

tangential issue brought up by this ticket that i've created new issues for:
- Min-width for timeline events. Render events by computed width. - #122
- Drag indicator for date/time - #123

the second one is not as important because you can actually put YMD date formatters in [timeFormat](http://fullcalendar.io/docs/text/timeFormat/)

**Comment by MacTwister** [comment]
Oh shoot, thought I replied. I tried the suggestion as noted last. However I noticed some weird stuff. 

So the following configuration made my events still fill a whole month, although different to before, as if it was making an event 31 days long.
```
slotDuration: { months: 1 },
snapDuration : '24:00:00',
```

However, when I use ```slotDuration: { days: 31 }``` then I get the events starting on the specified date, or so it seemed. 
Each month did not start on the 1st. Similar to the screen shot from @jasonEXA , look at the header labels for the month/day, under each month is not always 1st. So If I had a event for 2nd of march, that event actually appeared to start somewhere like 28th February. But as you said, not all months are 31, so if I could use the ```months: 1``` that might resolve it.

Additionally, the min-width feature, would be great because a lot of my events are a week or 2, and then I don't see the contents properly. Any rough timeline when you would get into #122 ?

**Comment by jasonEXA** [comment]
@MacTwister using slotDuration {months: 1} gets the following output,
![image](https://cloud.githubusercontent.com/assets/9958408/12785482/bc028a8e-cab2-11e5-88ac-e2b7f5efc0b0.png)

As you can see, the day as such is not specified as it was in my previous screenshot.  However, because the slotDuration is 1 month, the events appear to be ending at the end of the month as opposed to somewhere in between.

**Comment by MacTwister** [comment]
@jasonEXA I was unable to get the event box to start on the correct date like you have shown. So that would be my first issue to resolve, how you are able to get it working using months=1.

Yes, about the end, I believe there is also an issue there, as the event box should stop on the end date or minWidth, which ever is larger.

**Comment by jasonEXA** [comment]
@MacTwister Apologies for that.  I had also changed **duration to months=12** along with **slotDuration to months=1**.
Please bear in mind, this is only for display purposes in the month view.  I am currently experimenting with different views ranging from month to day and am looking at using the day/week view to actually controll the start/end time of the event.  I am assuming this view is for a high level overview for what is happening during the year.  As such, I have limited the control for further granularity of the scheduling to the other views.
Using this view will have the event occupying the entire month as mentioned earlier.

**Comment by MacTwister** [comment]
@jasonEXA I do not really follow you? For my project yes I am trying to display a whole year overview of all events (which are all full day events). So I don't know if you were able to get it working, or also have some things not fully working yet.

I created a JSBin to play around with. If you play with months=1 or days=31 you will see the differences. So the days version is what I would like visually but its not actuary because of some months have 30 days. And also the min event width would be great to working soon.

http://jsbin.com/lulehojizo/1/edit?js,output

**Comment by MacTwister** [comment]
@arshaw Did you see the jsbin i created? I can not get the events starting on the correct date, if I am using ``months: 1```. Any Ideas?

http://jsbin.com/geqitayalo/edit?js,output (updated js files)

**Comment by arshaw** [comment]
@MacTwister hmm things look strange there. must be a bug when using `{months:1}`. I'll investigate.

**Comment by Monigingir** [comment]
Hi, 

Was this issue resolved as I am facing the same issue when I use slotDuration as { months : 1 }
