### ISSUE TITLE
minTime/maxTime still messed up

### ISSUE THREAD

**Issue by agapas** [fullcalendar/fullcalendar-scheduler#96]
Timeline view:

When the properties minTime, maxTime and businessHours are configured there is a problem with the styles in the first day, it doesn't show the grey color at the beginning. Example: http://jsbin.com/yubufuxenu/3/edit?js,output

The problem could be resolve by adding style: "left: 0px;" in the first div that has the classes "fc-nonbusiness fc-bgevent" 

Thanks

**Comment by floriancargoet** [comment]
I have the same problem. Without the left: 0px, the event is at an incorrect position.
Setting `minTime` different from "00:00:00" is enough to trigger the bug for events starting before minTime (or starting on a past day).

**Comment by floriancargoet** [comment]
The top position is also incorrectly computed when there are several events affected by this bug.

**Comment by arshaw** [comment]
the most recent version of scheduler fixed a minTime bug. I've updated your JSBin to the latest:
http://jsbin.com/riyigijowo/edit?js,output

As you can see, things look much better. But I an still noticing a bug that the green and red events are extremely compressed. They shouldn't even be visible because their range is outside of the visible range.

I'll keep this ticket to represent this new bug. thanks!

**Comment by floriancargoet** [comment]
There's a problem with event2 in the latest jsbin: the end time is 22:00 but the event ui stops at 17:30. It played with end times and the bug appears when end > maxTime.

**Comment by arshaw** [comment]
thanks for pointing that out. will get that fixed too

**Comment by arshaw** [comment]
updated jsbin with latest version, fixed: http://jsbin.com/juyefefani/1/edit?html,output

**Comment by arshaw** [comment]
just released in [v1.2.1](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.2.1)
